version: "{build}"

hosts:
  quic.clemente.io: 127.0.0.1

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\mholt\caddy

environment:
  GOPATH: c:\gopath

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.9.windows-amd64.zip
  - 7z x go1.9.windows-amd64.zip -y -oC:\ > NUL
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/FiloSottile/vendorcheck
  # Install gometalinter
  - go get github.com/alecthomas/gometalinter

build: off

build_script:
  - go build -o buildOutput\caddy.exe 

test_script:
  - gometalinter --install
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
  - vendorcheck ./...
  - go test -race ./...

after_test:
  - golint ./...
  - ls -l

artifacts:
  - path: buildOutput\caddy.exe
    name: CaddyEXE 

deploy:
  provider: Webhook
  url: https://caddyserverbuilds.toflidium.com/hook_2141174C-7CC8-4E8B-A3F8-9A0B55FE97BB/webhook_appveyor.php
