version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\mholt\caddy

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 0

install:
  - go get golang.org/x/tools/cmd/vet
  - echo %GOPATH%
  - go version
  - go env
  - go get -t ./...

build_script:
  - go vet ./...
  - go test ./...